# frozen_string_literal: true
# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

# stub: huawei_e5180_api 0.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = 'huawei_e5180_api'
  s.version = '0.1.1'

  if s.respond_to? :required_rubygems_version=
    s.required_rubygems_version = Gem::Requirement.new('>= 0')
  end
  s.require_paths = ['lib']
  s.authors = ['Marcin Nowicki']
  s.date = '2015-04-30'
  s.description = 'Api support for Huawei E5180 LTE modem in ruby.'
  s.email = 'pr0d1r2@gmail.com'
  s.extra_rdoc_files = [
    'LICENSE',
    'README.md'
  ]
  s.files = [
    '.document',
    '.rspec',
    'Gemfile',
    'Gemfile.lock',
    'Guardfile',
    'LICENSE',
    'README.md',
    'Rakefile',
    'VERSION',
    'huawei_e5180_api.gemspec',
    'huawei_e5180_monitoring.gemspec',
    'lib/huawei_e5180_api.rb',
    'spec/fixtures/cassettes/check_notifications.yml',
    'spec/fixtures/cassettes/converged_status.yml',
    'spec/fixtures/cassettes/current_plmn.yml',
    'spec/fixtures/cassettes/mobile_dataswitch.yml',
    'spec/fixtures/cassettes/status.yml',
    'spec/fixtures/cassettes/status_info.yml',
    'spec/fixtures/cassettes/traffic_statistics.yml',
    'spec/huawei_e5180_api_spec.rb',
    'spec/spec_helper.rb',
    'spec/support/vcr.rb'
  ]
  s.homepage = 'http://github.com/pr0d1r2/huawei_e5180_api'
  s.licenses = ['MIT']
  s.rubygems_version = '2.4.5'
  s.summary = 'Api support for Huawei E5180 LTE modem in ruby.'

  if s.respond_to? :specification_version
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0')
      s.add_runtime_dependency('activesupport', ['>= 0'])
      s.add_runtime_dependency('mechanize', ['>= 0'])
      s.add_development_dependency('bundler', ['~> 1.0'])
      s.add_development_dependency('guard-bundler', ['>= 0'])
      s.add_development_dependency('guard-cane', ['>= 0'])
      s.add_development_dependency('guard-rspec', ['>= 0'])
      s.add_development_dependency('guard-rubocop', ['>= 0'])
      s.add_development_dependency('guard-rubycritic', ['>= 0'])
      s.add_development_dependency('jeweler', ['~> 2.0.1'])
      s.add_development_dependency('rdoc', ['~> 3.12'])
      s.add_development_dependency('rspec', ['>= 0'])
      s.add_development_dependency('simplecov', ['>= 0'])
      s.add_development_dependency('vcr', ['>= 0'])
      s.add_development_dependency('webmock', ['>= 0'])
    else
      s.add_dependency('activesupport', ['>= 0'])
      s.add_dependency('bundler', ['~> 1.0'])
      s.add_dependency('guard-bundler', ['>= 0'])
      s.add_dependency('guard-cane', ['>= 0'])
      s.add_dependency('guard-rspec', ['>= 0'])
      s.add_dependency('guard-rubocop', ['>= 0'])
      s.add_dependency('guard-rubycritic', ['>= 0'])
      s.add_dependency('jeweler', ['~> 2.0.1'])
      s.add_dependency('mechanize', ['>= 0'])
      s.add_dependency('rspec', ['>= 0'])
      s.add_dependency('rspec', ['>= 0'])
      s.add_dependency('vcr', ['>= 0'])
      s.add_dependency('vcr', ['>= 0'])
      s.add_dependency('vcr', ['>= 0'])
    end
  else
    s.add_dependency('mechanize', ['>= 0'])
    s.add_dependency('mechanize', ['>= 0'])
    s.add_dependency('rdoc', ['~> 3.12'])
    s.add_dependency('rspec', ['>= 0'])
    s.add_dependency('simplecov', ['>= 0'])
    s.add_dependency('vcr', ['>= 0'])
    s.add_dependency('webmock', ['>= 0'])
    s.add_dependency('webmock', ['>= 0'])
    s.add_dependency('webmock', ['>= 0'])
    s.add_dependency('webmock', ['>= 0'])
    s.add_dependency('webmock', ['>= 0'])
    s.add_dependency('webmock', ['>= 0'])
    s.add_dependency('webmock', ['>= 0'])
    s.add_dependency('webmock', ['>= 0'])
  end
end
